feat: allow using authorization query parameter
bpolaszek/freddie pull request #16
Opened 2022-06-20 19:03 UTC by azjezz

This PR implements query authorization which was recently added to mercure spec.

some performance improves are also added to existing token extractors to cover edge cases, and to not take into account invalid tokens as soon as possible.

refs:

- https://github.com/dunglas/mercure/pull/655
- https://github.com/dunglas/mercure/issues/387

2022-06-20 22:07 UTC, dunglas approved these changes

2022-06-21 06:50 UTC, bpolaszek requested changes
Welcome @azjezz and thanks for the PR!

LGTM - just some minor comments.

2022-06-21 16:27 UTC, azjezz commented on src/Security/JWT/Extractor/AuthorizationHeaderTokenExtractor.php
> +        return substr($authorizationHeader, 7);
is there a reason for having "Bearer" and "Authorization" as a parameters rather than constants?

2022-06-21 20:06 UTC, bpolaszek commented on src/Security/JWT/Extractor/AuthorizationHeaderTokenExtractor.php
> +        return substr($authorizationHeader, 7);
I have no relevant reason of hardcoding it - some people could use an `X-Token` header with no prefix instead for instance - for example to deal with some weird browser behavior (looking at you, Safari) which won't send an `Authorization` header again after being 302 redirected.

2022-06-23 16:35 UTC, azjezz commented on src/Security/JWT/Extractor/CookieTokenExtractor.php
> +        if (!is_string($token) || strlen($token) < 41) {
this is the minimum length of a valid token.

2022-06-26 08:28 UTC, bpolaszek commented
How about adding that new extractor [here](https://github.com/bpolaszek/freddie/blob/main/src/Security/JWT/Extractor/ChainTokenExtractor.php#L18)?

2022-06-26 08:30 UTC, bpolaszek commented
How about adding that new extractor [here](https://github.com/bpolaszek/freddie/blob/a6890c843849ca257697ab7854377925a6811d7c/src/Security/JWT/Extractor/ChainTokenExtractor.php#L18) instead? 
Meaning the authorization token through query param would have the heaviest weight?

2024-03-19 14:42 UTC, bpolaszek commented
I'm opening a new PR based on this one, I'll co-author you. Thanks! 🙏

2024-03-19 14:42 UTC, closed without merging

2024-03-19 15:43 UTC, dunglas commented
I plan to deprecate this feature as it's being deprecated from OAuth, so maybe don't bother implementing it?

2024-03-19 16:19 UTC, bpolaszek commented
Oh, do you have a link about why it's being deprecated?

2024-03-19 22:58 UTC, dunglas commented
See https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#section-4.3.2

The browser history isn't a problem with EventSource, but still it isn't a good security practice as the token will likely be logged by reverse proxies, web servers etc.

2024-03-20 09:16 UTC, bpolaszek commented
Makes sense, but there are some cases where using a query param could be more convenient, even if less safe.

I remember facing important CORS issues when using the `mercureAuthorization` cookie (even with `withCredentials: include` - some browsers were fine with it, some weren't), but also with the `Authorization` header (that Safari does not forward whenever the endpoint responds 302, for example).

So I'd consider keeping the feature while displaying a warning in the documentation.